### ISSUE TITLE
Azərbaycandan xaricdə yaşayaraq remote işləyib, Azərbaycandaki hesaba ödəmə almaq mümkündürmü ?

### ISSUE THREAD

**Issue by RaminMammadzada** [ShahriyarR/remote-work-questions#1]
Başqa ölkədə yaşayan Azərbaycan vətəndaşı ( misalçün Türkiyə ), o ölkədə yaşayaraq Azərbaycanda qeydiyyatda olan bir vergi ödəyicisi olub, ödəniş qəbul edə bilər mi remote iş üçün ? Şirkətlər bunu qəbul edirmi ? Təcrübəsi olan varmı bu mövzuda ?

Remote çalışmaq üçün, mütləq hal hazırda rəsmi qeydiyyatda olduğun yerdən mi çalışmalısan ?

Bunu soruşmağımın səbəbləri:
- yasadığım xarici ölkədə verginin yüksək olması
- rəsmi qeydiyyat məsələlərində problem yaşanması

**Comment by ShahriyarR** [comment]
* Təbii ki,
Belə ki, bankda sahibkar hesab açdıqda, həmin hesaba bağlı business card əldə etmək olar.
5 illik bir bank kartı ilə istənilən yerdə daxil olan puldan istifadə etmək olar. Bu zaman sadəcə xarici ölkənin əlavə konvertasiya haqqı tutula bilər ki, bu da elə də böyük məbləğ olmamalıdır fikrimcə.
* Xarici şirkət üçün, bizim fiiziki olaraq harda olmağımızın yalnız timezone olaraq uyğunluğu söhbəti aparılır, yerli qanunvericilik onları bağlamır və maraqlandırmır. Bəli Türkiyədə qalıb, Azərbaycanda vergi ödəyib, Azərbaycanda aldığınız kartdakı pulla yaşaya bilərsiniz.
* Remote çalışmaq üçün fərqi yoxdur hardasan, əsas bank hesabı vermək lazımdır ki, pulu göndərə bilsinlər.

**Comment by RaminMammadzada** [comment]
Başa düşdüm. 
Təşəkkür edirəm ətraflı izaha görə.

**Comment by ShahriyarR** [comment]
Bu suali bagli elan edirem, cavabi da README-ye elave edirem.
Sual ucun teshekkurler :)

**Comment by Muzafferus** [comment]
Salam hər vaxtınız xeyir. Sual bağlı olsa da belə bir əlavəm olacaqdı.

Bütün bu VÖEN açma hesab açma və sairə, prosesləri üçün hökmən Azərbaycana qayıtmalıyam? (Hal hazırda Türkiyədəyəm və ilk dəfə remote işləyəcəyim üçün heç bir hesabım yoxdur)

**Comment by themisir** [comment]
> Bütün bu VÖEN açma hesab açma və sairə, prosesləri üçün hökmən Azərbaycana qayıtmalıyam? (Hal hazırda Türkiyədəyəm və ilk dəfə remote işləyəcəyim üçün heç bir hesabım yoxdur)

Mən maksimum online etməyə çalışdım amma ki, bütün variantlarda ən azı bir dəfə asan xidmətə getməli olduğumu gördüm (ya asan imzanı öncə vətəndaş sonra vöen hesabına bağlamaq üçün, yada asan imza olmadan vöen açmaq istəsəniz bu zaman da yenə asan xidmətə getmək lazımdır ki).

Əlavə olaraq bizdə bankar onlayn xidmət versə də ən azı bir dəfə banka getməyə işiniz düşəcək, imza nümunəsi falan istəyirlər bəzən.
