### ISSUE TITLE
Qaimə

### ISSUE THREAD

**Issue by fermanquliyev** [ShahriyarR/remote-work-questions#10]
Mən bir mühasiblə söhbət edərkən mənə dedi ki, əgər vöenə bağlı bank hesabına pul köçürülürsə onun qaiməsini kəsməlisən ki, bəs bu xidməti göstərmişəm və qarşılığında bu pulu almışam. Sizdə belə bir şey olub?

**Comment by ShahriyarR** [comment]
Boş söhbətdi. 
Məsələn, Kanada şirkəti nə bilir bizim geydirmə qaimə-faktura forması nədi nə deyil :)
Ehtiyac yoxdur və tələb də olunmur.

**Comment by fermanquliyev** [comment]
Onu anlayıram ama mühasib mənə onu sanki qaiməni yazmalıyam kanadadakı şirkət üçün yox  burda vergilər nazirliyinə bildirmək üçün ki, mən hesabıma köçən bu pulu bu xidmət qarşılığında bu mənbədən almışam

**Comment by ShahriyarR** [comment]
Boş söhbətdi N2.
Ehtiyac yoxdur. Remote işləyənin bank hesabına pul gəlir o da həmin puldan vergisini ödəyir vəssəlam.
