### ISSUE TITLE
DSMF və Siğorta

### ISSUE THREAD

**Issue by murad755** [ShahriyarR/remote-work-questions#12]
Salam. DSMF və Siğorta ödənişlərini hara və necə ödəmək lazımdı? Online ödəmək mümkündü? Mümkün olduğu halda, hansı məlumatlar (voen, istifadeci və s) lazımdı ödənişi düzgün yerinə yetirmək ücün? Ümumi olaraq borcumun olmağını, varsada nəgədər ödəniş etməli oldugumu gorə biləcəyim bir platforma var?

**Comment by ShahriyarR** [comment]
Onlayn Kargüzarlıqdan mümkündür bu mən bilən amma yenə də daha dəqiq soruşaram camaatdan.

**Comment by ShahriyarR** [comment]
GPP.az-dan odenish edirik butun borclari.
"Shexsi hesab vereqesi"-de en axirda vergi borcu gorsenir.

**Comment by ShahriyarR** [comment]
GPP.az-dan borc odeyerken:
* 111130 - Fiziki shexslerin diger gelirlerinden gelir vergisi
* DSMF borcu odeyerken:
Muzdla işləməyənlərin fərdi sahibkarlıq fəaliyyəti üzrə ödənilən sosial ayırmalar:
121380 - Digər sahələrdə sahibkarlıq fəaliyyəti ilə məşğul olan fiziki şəxslər üzrə ödənilən sosial ayırmalar

* Icbari de hemcinin orda qeyd olunur Diger sahelerde bla bla bla
