### ISSUE TITLE
Remote part time 

### ISSUE THREAD

**Issue by erkin98** [ShahriyarR/remote-work-questions#14]
Salam, adıma bir neçə full+part time müqavilə var iş yeri Azərbaycan olmaq üzrə, xaricdən yeni part time remote iş görürsəm bu problem olmaz ki?

**Comment by ShahriyarR** [comment]
Xarici remote iş təklif edən şirkətlərin 99%-i yalnızca onlar üçün full-time çalışmağınızı tələb edir. Yani part-time təklif edənlərini mən görməmişəm.
Təbii ki, sonradan üstü açılsa ki, eyni anda bir neçə şirkət üçün çalışırsınız bu imzalanan kontraktın qaydalarının pozulması deməkdir. Düşünmürəm ki, xarici şirkət əziyyət çəkib sizi məhkəməyə verəcək amma ki, həmin şirkət yəqin ki, sizdən sonra bütün azərbaycanlıları işə götürməyəcək. Ümumiyyətlə bu kimi işlərdə çox diqqətli, disiplinli və etibarlı olmaq lazımdır ki, sonradan kimisə refer etdikdə həmin azərbaycanlı da işə girə bilsin, iş sahibi olsun. Bu işin mənəvi və hüquqi tərəfi.
O ki qaldı deyək ki, eyni anda 3 iş görüb çatdıranlara şəxsən mən həsəd aparıram :) Özüm heç vaxt eyni anda 1 işdən artıq işdə çalışmamışam, sadəcə nə enerjim qalır nə də həvəsim.
Vergi Xidməti üçün isə bu lap əladır, daha artıq qazanırsınız, deməli daha artıq vergi verirsiniz.

**Comment by erkin98** [comment]
İşə götürən bildirdi ki,iş part-time olacaq bu halda yəqin ki,siz deyənlər yaşanmaz :)

**Comment by ShahriyarR** [comment]
Yəqin ki :)

**Comment by ShahriyarR** [comment]
Bu suali README-ye elave etdim.
Issue-nu baglayiram.
