### ISSUE TITLE
Şəhadətnamə dublikatinin alınması

### ISSUE THREAD

**Issue by KananMahammadli** [ShahriyarR/remote-work-questions#15]
"Bankda hesabın açılması məqsədilə şəhadətnamə-dublikatin alınması üçün ərizə" ni doldurarkən remote iş üçün hansı növ bank hesabı seçilməlidir?

![IMG_20211102_092029](https://user-images.githubusercontent.com/53794602/139796131-f8c92379-a2a9-4010-8afe-af1a4d10f91c.jpg)

**Comment by ShahriyarR** [comment]
Əgər dollarla qəbul edirsinizsə, 1 Cari Hesab AZN üçün və 1 Cari Hesab da Dollar üçün göndərmək lazımdır.
Yəni hesabın tipi Cari-dir.
Eyni qaydada deyək ki, daha sonra siz euro ilə ödəniş almağa başladınız, o zaman da 1 Cari Hesab Euro göndərmək lazım olacaq.
Yəni istənilən valyuta üçün 1 Cari AZN + 1 Cari <valyuta> növü açılmalıdır.
