### ISSUE TITLE
Sual: GPG vasitəsilə ödəniş edəndə, tranzaksiya neçə gün çəkir normalda?

### ISSUE THREAD

**Issue by orkhan-huseyn** [ShahriyarR/remote-work-questions#17]
İkinci gün  ödəniş eləmişəm, hələ oturmayıb:D

**Comment by ShahriyarR** [comment]
Hec bir fikrim yoxdur :D yeqin 3 gune falan)

**Comment by orkhan-huseyn** [comment]
İnşallah :D

**Comment by orkhan-huseyn** [comment]
Deməli elektron formada ödəniş ediləndə 1 iş günü ərzindədi, elektron olmayanda 2 iş günü.
Məndə isə 2-ci gün DSMF-ni ödədim 5-ci gün ödəniş tam oturdu (ayaq üstə qalmışdı) və borcum silindi.
Təxmini 3 gün hesab edin özünüz üçün.
