### ISSUE TITLE
Payoneer kart vergi

### ISSUE THREAD

**Issue by isco232** [ShahriyarR/remote-work-questions#18]
Salam, 

İşlədiyim şirkət yalnız payoneer üzərindən ödənişlər edir.

Qocalanda pensiya filan istəmirəm.

Payoneer kartdan maaşımı çəkib vergi ödəməsəm olarmı?

Və ya ödəməliyəmsə, necə ödəyim? Hesab yoxdu axı burdakı bankda.

P.S. Hal hazırda bir dəfəyə 1400$ çıxartmaq olur.

**Comment by ShahriyarR** [comment]
Qocalanda pensiya üçün ödənilmir Vergi - ümumən vergi qanunun tələbidir və ölkə büdcəsinin yarıdan çoxu vergilər hesabına formalaşır. Sosial Müdafiə(DSMF) üçün ödənilən puldan isə bütün ölkədəki sosial ödənişlər formalaşır yəni, veteranlar, müəllimlər, əlilliyi olanlar, təqaüdə çıxanlar, ünvanlı sosial yardımlar, sosial layihələr və s. üçün xərclənir. Yəni DSMF ödənişi də sənin pensiyan üçün deyil, qanunun tələbi olduğu üçün, həmçinin adı çəkilən ölkə əhalisinə təsir etdiyi üçün ödənilir(təbii ki, ən sonda sənin də pensiya yaşın çatanda sənə də ödəniləcək - və təbii ki, həmin vaxt daha cavan adamların ödənişlərinə görə formalaşan fonddan ödəniləcək).

Payoneer kart-la bağlı bizim vergi qanunvericiliyində hər hansı maddə gözümə dəyməyib və ümumən xarici bank kartından vergi tutmaq anlayışı inanmıram olsun. Yalnız nağdsız ödənişlər zamanı konvertasiya haqqı tutula bilər, həmçinin nağdlaşdırarkən faiz tutular.
1400$-a nə qədər faiz tutur çıxardıqda?

**Comment by isco232** [comment]
900$da 32$ vergi tutulur hazırda. Bunun 16$ı bizim bank tərəfindən, digər 16$ı isə xarici bank tutur. 

Nə qədər böyük məbləğ çəkilsə komissiya o qədər azalır.

**Comment by ShahriyarR** [comment]
Bu vergi deyil, fee-dir, yəni komissiya. Hardasa, 3.5% tutulur 900$-da. Teqriben 1,8% bizim bank tutub. Niye mehz bu qeder oldugunu sorushmaq lazimdir bankdan. 0.8%-i bizim bank fee-dirse, geride qalan 1% hardan niye tutulub onunla maraqlanmaq olar.

**Comment by isco232** [comment]
Son olaraq belə anladım ki, tam 100/100 vergi tələbi yoxdur mənim qeyd etdiyim situasiyada.

**Comment by ShahriyarR** [comment]
Hə, Payoneer kart üçün vergi verən görməmişəm.
Ümumən xarici şirkətlər maaşın üzərinə bizim təqdim etdiyimiz(hesabladığımız) vergi məbləğini də qoyub göndərdiyi üçün istənilən halda o pulu şirkət ödəmiş olur, bu səbəbdən şəxsən mənə pulu necə harda qəbul etməyimin əhəmiyyəti yoxdur. Hə, o vergi üçün göndərilən puldan qabağa düşmək istəyənlər vergidən yayınmağın müxtəlif üsullarını tapırlar və hər yerdə də danışırlar, lakin cinayət tərkibi olduğu üçün biz belə yolları məsləhət görmürük, yaymırıq, paylaşmırıq.
2015-ci ildən remote çalışıram o vaxtdan da vergi verirəm - Azərbaycan Respublikasının Vergi Qanunvericiliyinə uyğun olaraq.
Qeyd: Payoneer tamamilə qanuni vasitədir.
