### ISSUE TITLE
Payoneer kart fərqi

### ISSUE THREAD

**Issue by fermanquliyev** [ShahriyarR/remote-work-questions#2]
Payoneer kart ilə ödəniş almağın bu cür ödəniş almaqdən nə kimi mənfi-müsbət fərqləri var?

**Comment by ShahriyarR** [comment]
Hormetli vergi odeyicisi olmagin bir sira ustunlukleri var:
* DSMF odenishi oldugu ucun qojalanda pensiya sohbeti gedir :)))
* Ipoteka goturende 2 il erzinde bank hesabina daxil olan vesait ve hemcinin 2 il erzinde odediyiniz vergiler teleb olunur. Bunlar yerinde olsa Ipoteka almaq her hansi problem ola bilmez. Eyni hadise kredit goturende de bash verir - heyatdi bilmek olmur bir de gordun lazim oldu.
* Medaxili, mexarici, borcu-xerci hesablamaq daha rahatdi, bash da az yorulur, engineer olaraq tenbel adamam men 5%-i tutun bashim sakit olsun mentiqi ile gedirem.

Paynoneer kart men 2015-de istifade etmeye calishmisham onda da bele bir problem olmushdu ki, bir defeye yalniz 300$ cixartmaq olurdu, her defe cixardanda 1.5%-2% tuturdu + nese elave de bir fee var idi. Odur ki, imtina etmishdim, yani hesab kitab edende serf etmemishdi, cunki o vaxti remote ishleyenler sadeleshdirilmish vergi odeyicisi gedirdi ve o da rayonda 2% bakida 4% idi. 
Bashqa her hansi payoneer-e qarshi arqumentim yoxdur. Belke kimse daha yaxshi biler ama menim tecrubemde bele idi.

**Comment by ShahriyarR** [comment]
Sual ucun teshekkurler.
Suali ve cavabi README-ye qeyd etdim.
