### ISSUE TITLE
Payoneer kartla alınmış ödənişlərin/gəlirin rəsmiləşdirilməsi

### ISSUE THREAD

**Issue by avgasanov** [ShahriyarR/remote-work-questions#20]
Salam,

Payoneer kartıma vəsait köçürülüb. Bu pulu fiziki şəxsə (VÖEN-ə) bağlı bank hesabına köçürüb, vergi xidmətinə bəyan edib vergisini ödəmək istəyirəm. Bu zaman fiziki şəxs kimi ödədiyim vergidən əlavə hansısa vergi ödəməliyəm? Və ya vergi xidmətinə hansısa müqavilə təqdim etməliyəm, gəlirin hardan olduğunu göstərmək üçün?
Təbii ki, Payoneer kartdan birbaşa nəğdləşdirmək imkanı var, ancaq qanuni şəkildə vergini ödəmək istəyirəm.

Qısa olaraq:
1) Payoneer kart hesabından VÖEN-ə bağlı hesaba köçürmə edərkən hansı vergilər tutulur/ödənməlidir.
2) Payoner kart hesabından VÖEN-ə bağlı hesaba köçürmə edərkən vergi xidməti/bank tərəfindən hansı əlavə sənədlər tələb olunur (xidməti/mülki müqavilə kimi)?

Related to #18

**Comment by ShahriyarR** [comment]
Ele tesevvur edin ki, sizin Payoneer  kartiniz ele xarici shirketdir.
Bu zaman shirket siz ozunuzsuz(payoneer kartiniz), qebul eden de yene ozunuzsunuz(sahibkar hesabiniz).
Yani shirket sizin Payoneer hesabiniza, siz de sahibkar hesabiniza gonderseniz, ele shirket gondermish kimidir.
Bele olan halda bu repo-da evvelden axira behs edilen vergi prosedurlari eyni ile size de shamil olunur.
1-ci suala cavab: bu repo-da bu suala cavablar verilib, vergi novu, hesab acilmasi, vergi hesablanmasi ve s.
2-ci suala cavab: yuxaridakilari nezere alaraq deye bilerik ki, elave hecne teleb olunmur. Umumiyyetle vergiler her hansi sened istemir adamdan, yalniz bank isteye biler muqavilenin suretini. O da ki, Payoneere pul gonderen shirketin muqavilesini gostermek olar.

**Comment by avgasanov** [comment]
Cavab üçün təşəkkür edirəm. Bəli, repo-da müzakirə edilən vergilər bilirdim. Hər ehtimala ödənişi göndərən tərəfindən əlavə hansısa vergilərin olmasını dəqiqləşdirmək istəyirdim. Tam aydın oldu indi.
