### ISSUE TITLE
2 hesabım var

### ISSUE THREAD

**Issue by faridmzd** [ShahriyarR/remote-work-questions#23]
2 iş yerim var xaricdə. 3 hesabım var (EUR, USD, AZN(bank əməliyyatları üçün lazım olur dedilər)). 1 ay ərzində 2 hesabıma ödəniş olunubsa 2x(DSMF + İcbari tibbi siğorta) ödənilməlidir? və ya rüblük hesabat hər hesabəm üçün ayrıca verilir?

**Comment by ShahriyarR** [comment]
Yox, sadece 1 dsmf odenishi ve 1 icbari odenishi lazimdir. Her hesab ucun ayrica verilmir.
