### ISSUE TITLE
.

### ISSUE THREAD

**Issue by faridmzd** [ShahriyarR/remote-work-questions#25]

**Comment by ShahriyarR** [comment]
İlk öncə qeyd edim ki, bu repo-nun məqsədi vergi qaçırtmağı göstərmək yox, remote işləyənlərin vergilərə aid suallarını cavablandırmaqdır. Azərbaycanlı beyni belə işləməlidir - bütün xarici şirkətlər göndərilən pulun üzərinə sizin ödəyəcəyiniz vergini qoyur və elə göndərir, dolayısı ilə o pul onsuz da şirkət tərəfindən ödənilir.
Heç bir halda vergi qaçırtmaq təlkin oluna bilməz, bu cinayətdir. Mən bu kimi əməlləri dəstəkləmirəm.

Keçək suallara:
1. Hər 3 aydan bir banklar vergi orqanına hesabat göndərir. Əgər VÖEN ləğv olunubsa, lakin sahibkar hesaba pul gəlirsə, növbəti ay ərzində onsuz da xəbərləri olacaq vəı bu vergi qaçırtmaqdır.

2. Elə təsəvvür edək ki, xaricdən X şəxs və ya şirkətdən hər ay eyni və ya fərqli məblğdə ödəniş gəlir. Birinci ay deyərsən ki, dostundu, ikinci ay deyərsən ki əmi oğludu amma 3-cü ayda maliyyə monitorinqi o pula blok qoyacaq və bank çağırıb soruşacaq ki, pulun mənbəyi və səbəbi nədir. Belə çıxır ki, müqavilə göstərməlisən, müqavilə göstərdikdə isə xidmət əsasında baş verir. Xidmət göstərirsənsə vergi verməlisən. Beləcə məcbur VÖEN açıb, sahibkar hesabı açıb rəsmi qaydada işləməli olursan.

**Comment by farid-mzd** [comment]
Çox sağ olun.Bu arada "Azərbaycanlı beyni" termininin yaranmasına səbəblərdən biri də verilən bu qədər verginin qarşılığının olmaması ola bilər. Hər kəs təbii ki, öz dövlətinin inkişafı üçün vergi verməlidir.Ama eyni qayda da "məmurları"  doyuzdurmamalıdır.
