### ISSUE TITLE
ITS/MDSS: ayliq vergiler

### ISSUE THREAD

**Issue by rwp0** [ShahriyarR/remote-work-questions#28]
Gelir vergisinden basqa ayliq ITS/MDSS vergileri her (yerli ve xarici) sirkete gore odenilmelidir yoxsa ancaq bir defe?

**Comment by ShahriyarR** [comment]
İTS - mən 1 nəfərəm(mikro sahibkar) və tibbi sığortanı da özüm üçün ödəyirəm. Hansı ay ödəniş gəlibsə o ay üçün ödənilir, cəmi bir dəfə.
5 şirkətlə işləyən eyni mənəm və məni də cəmi 1 dəfə tibbi sığortalayırlar :D
MDSS - mən 1 nəfərəm(mikro sahibkar) və sosial müdafiə pulunu özüm üçün ödəyirəm. Hansı ay ödəniş gəlibsə o ay üçün ödənilir, cəmi bir dəfə. 
5 şirkətlə işləyən eyni mənəm və mən də cəmi 1 dəfə sosial sığortalanıram.
