### ISSUE TITLE
Dublikat hesab açılarkən o hesaba bağlı olan bank kartı 

### ISSUE THREAD

**Issue by fermanquliyev** [ShahriyarR/remote-work-questions#3]
Dublikat hesab açılarkən o hesaba bağlı olan bank kartı avtomatik olaraq təqdim olunur? Yəni default olaraq həmin hesaba bağlı kart verilir pulu atmdən çəkmək, nağdsız-online alışveriş üçün?

**Comment by ShahriyarR** [comment]
Dublikat hesab acarken secdiyiniz banki duzgun arashdirmaq lazimdir.
Adeten Sahibkar paketi deye bir sheyler olur ve ola bilir. Gerek bankdan sorushasiniz.
Sahibkar hesabina bagli bank kartinda atm-den cekme qaydasi ferqli ola biler onu da gerek deqiqleshdiresiniz. 
Online nagdsiz ishler ucun ise idealdir.
+ xaricde gedib yashayanda meselen, 3 ay Turkiyede falan hansisa turistik yerde ishleyende odenish gelende bu kartla yashamaq olur :)

**Comment by ShahriyarR** [comment]
Sual ucun teshekkurler.
Suali ve cavabi README-ye qeyd etdim.
