### ISSUE TITLE
Asan Imza mutleq sekilde 01.01.2024 tarixindan zeruri olaraq butun sahibkarlarda olmalidir.

### ISSUE THREAD

**Issue by sabuhigr** [ShahriyarR/remote-work-questions#38]
Hesabi bu ilin avqust ayinda acdirmisham ve yeni VOEN acdiran shexslerden ASAN IMZA mutleq shekilde istenir.
Hemcinin e-taxes daxil olanda da bildirish kimi gosterilir.

**Comment by ShahriyarR** [comment]
Bunu PR kimi gonderin zehmet olmasa Merge edek muvafiq hisseye.
Teshekkurler.

**Comment by sabuhigr** [comment]
Hazirdi

**Comment by sabuhigr** [comment]
#39 PR
