### ISSUE TITLE
Dublikat hesab açılarkən hesabın valyutasi və bank secimi

### ISSUE THREAD

**Issue by murad755** [ShahriyarR/remote-work-questions#4]
Dublikat hesab ucun bank seçiminin guclu bir onəmi var yoxsa fərg eləmir? Fərg edirsə hansi bankdan hesab açmaq daha əlverişlidi? Bank hesabının hansı valyuta uzərindən açmaq daha düzgündu? Fərz edək ki vəsait $-ilə alınirsa o zaman ustunlük $ hesabına verilməlidi yoxsa ₼?

**Comment by ShahriyarR** [comment]
Qanunvericiliyə əsasən, xarici valyutada cari hesab(bizim halda dublikat hesab) açarkən AZN hesabı da olmalıdır.
Yəni onsuz da, bank bunu sizdən istəyəcək. Odur ki, elə şəhadətnamə dublikat göndərəndə  AZN və valyuta üçün göndərilsə yaxşıdır.
Daxil olacaq məbləğ dollardısa təbii ki, dollar hesabı + azn hesabı açılmalıdır. Eurodursa, euro hesabı.
Bizim banklar arasında ağlabatan heç bir fərq görə bilmirəm, yeganə fərq hansının mobil bankingi yaxşıdı ya yox, hansı bank sahibkar hesabına kart təqdim edir və.s-dir. Dəhşətli heç bir fərq görmürəm, bütün banklarda xidmət və ümumiyyətlə 21-ci əsr suallarına cavab vermək aşağı səviyyədədir. Biri heç bir qanuni əsas olmadan xarici müqaviləni tərcümə elətdirmək istəyir, digəri başa düşmür fəaliyyətimiz nədir...
Mən qədimdən Access-lə işləyirəm o da ki, 20 yanvar filialında gedib çek kitabçası ilə növbə götürüb gözləyirdim, baxmayaraq ki, sahibkaram :)
