### ISSUE TITLE
Fiziki şəxs hesabıma  freelance işdən pul gəlməsi üçün müqavilə mütləqdir?

### ISSUE THREAD

**Issue by elmankarimli** [ShahriyarR/remote-work-questions#6]
Məndən Bank Respublikada illik daxil olma 5000 AZNi keçəndən sonra müqaviləni istəmişdilər.  Mən yerli universitetlərdən birinə xidmət göstərirdim.

**Comment by ShahriyarR** [comment]
Ele bir muqavile istemelerinin her hansi qanuni esasinin olmasindan shubheliyem.
Cunki, remote ishleyende xarici shirketle independent contractor muqavilesi baglanir o da ingilisce olur.
Hemin muqavilenin notarial qaydada tercumesi olmadan, bank onu neynir mene namelumdur :)
Mence sadece her ehtimala qarshi papkaya falan tikirler vesselam.

Sahibkar hesabina limitsiz pul daxil ola biler, adi ustunde bu adam sahibkardir 5000 limit sohbeti ola bilmez. Ayliq nagdlashdirma limiti var onu da Vergi Xidmeti teyin edir.

**Comment by elmankarimli** [comment]
Mence de cox mentiqsiz bir teleb idi.  Ama hell edildi. Ola bilsin, cirkli pulların yuyulmasından qorxurlar. Vergi bes pulun menbeyi ile bagli sorgu gondere bilermi?

**Comment by ShahriyarR** [comment]
Cirkli pullarin yuyulmasini bizim qepik-qurushda axtarmasalar daha yaxshidi, kifayet qeder coxlu heqiqi axtarish yerleri var :)
