### ISSUE TITLE
Remote iş tapmaq üçün hansı ingilis dilli saytları məsləhət görərdiniz?

### ISSUE THREAD

**Issue by sudo-make-coffee** [ShahriyarR/remote-work-questions#7]

**Comment by ShahriyarR** [comment]
Linkedin, Turing, Toptal, remoteok ve Twitter-de meselen `Vuejs Jobs` hesablar olur, yani sonu + jobs yazib follow etmek olar ve ordan tutmaq olar.
Rus dilli ise djinni.co, jobs.dou.ua, work.ua, career.habr.com -> QEYD: bunlarda da ingilisce ishler olur.
