### ISSUE TITLE
Salam.Eger bir isim varsa ve eyni zamanda remote olaraq da islesem vergi baximdan musbet ve menfi terefi nedir?

### ISSUE THREAD

**Issue by emilefendi** [ShahriyarR/remote-work-questions#8]
Salam.Eger bir isim varsa ve eyni zamanda remote olaraq da islesem vergi baximdan musbet ve menfi terefi nedir?

**Comment by ShahriyarR** [comment]
Remote iş verən şirkət əgər part-time-a razı olmayıbsa, sizdən indiki işinizi tərk etməyinizi tələb edəcək onsuz da.
Belə ki, Linkedin və digər sosial şəbəkələrdə işlədiyiniz yeri yeniləməyinizi istəyə də bilirlər. 
Odur ki, 2 işi eyni anda aparmağı məsləhət görmürəm əgər şirkətdən gizli gedirsə bu.
Vergi Xidmətinə artıq vergi ödədiyiniz üçün onlar təbii ki, sevinəcəklər ki, əlavə vergi gəlir. Vergi xidmətinə bu müsbət təsir edəcək, kefləri düzələcək yəqin ki :)
Odur ki, hər hansı müsbət və mənfi tərəfini görə bilmirəm bu mənada.
