### ISSUE TITLE
Hesablama ilə bağlı

### ISSUE THREAD

**Issue by fermanquliyev** [ShahriyarR/remote-work-questions#9]
Hesablamanı apararkən 5%dən sonda niyə DSMFni və digər ödənişləri  vergidən çıxırıq ki? Onları verginin üstünə gəlməli deyil əksinə?
Nümunə üçün yazdığınız bu hesablamanı nəzərdə tuturam:
253.5 - 180.42 = 73.08

Mən asan xidmətdə vergi uçotuna yazılanda mənə hər ay 5% gəlir vergisi + 62.50 azn DSMF + 10 azn icbari tibbi sığorta dedilər

**Comment by ShahriyarR** [comment]
Çünki əgər DSMF-ni özümüz üçün ödəyiriksə onun 100%-ni xərc kimi göstərə bilirik.
Belə olan halda da `Xərcləri də qeyd edirik: 150 + 30.42 = 180.42.`
Toplanan xərci də yekun vergi məbləğindən çıxırıq `Yekun vergi məbləği 253.5 - 180.42 = 73.08.`

ASAN-dakı son məlumatdan belə çıxır ki, 62.50*3 hesabat dövründə xərc kimi göstərilə bilər.
Sığorta haqqının xərc kimi göstərə bilərik mi, gərək öyrənəsən.

**Comment by ShahriyarR** [comment]
@fermanquliyev suali cavablandirilmish hesab etmek olar?

**Comment by fermanquliyev** [comment]
Xərc kimi harada göstəririk? e-taxesdə hesababat doldurarkən?

**Comment by ShahriyarR** [comment]
Beli.

**Comment by fermanquliyev** [comment]
Çox sağolun. Hesabatı doldurmağin qısa videosunu çəksəniz dediyiniz hesablamalarla daha aydın olar deyə düşünürəm ki, hara neçə yazmaq lazımdır sizin nümunə rəqəmlərlə.

**Comment by ShahriyarR** [comment]
Hesabat doldurmaq qaydasi, videosu falan Youtube-da vergilerin resmi kanalinda olmalidir.
Ele de cetin bir shey deyil her ay gelen pulun 5%-ni hemin gunun mezennesine uygun hesablayib muvafiq ay ucun qeyd edirsen, xerc qisminde de yuxarida muzakire etdiyimiz qaydada doldurursan vesselam (3 * dsmf_ayliq_odenish + bank komissiyasi ve s.)

**Comment by fermanquliyev** [comment]
ASAN xidmətdə mənə deyildi ki, vergini 3 aydan bir ödəyə bilərsən ama dsmf və sığortanı ni gərək hər növbəti ay 20nə kimi ödəyəsən

**Comment by ShahriyarR** [comment]
Odenish gelibse hemin ay odeye bilersen beli. Men xatirlayiram ki, dsmf-ni de hesabat dovrunde odeyirdim.
Lakin, yeqin ki, ASAN xidmetde daha yaxshi bilerler.
Demeli her ay dsmf_ayliq_odenish + sigorta ode. Hesabat dovrunde de vergini.

**Comment by fermanquliyev** [comment]
![image](https://user-images.githubusercontent.com/33841624/117161358-e3b59e00-add2-11eb-8f64-874f24e58200.png)
Burada, hesabat doldurma yerində xərc kimi göstərmək yeri yoxdur siz dediyiniz kimi

**Comment by ShahriyarR** [comment]
Bes harda var?

**Comment by fermanquliyev** [comment]
Tapa bilmədim, sizin dediyin kimi bir şey. Xərc çıxmaq üçün. Burada 12000 mənim 3 aylıq göstərdiyim gəlirdir. 1800 olan xanaya məbləğin *20%*75% dən az olmayaraq bir rəqəm yazmağı tələb edir, sonra üçüncü xanada onun 25%ni göstərir. Vergi olaraq onu ödəməli olursan deyəsən

**Comment by ShahriyarR** [comment]
Yeqin ki, beledi.
Men xatirladigim qederi ile nese elave olmali idi ora xerc yazirdiq.
Yoxdursa ya deyisiklik olub ya da men sehv xatirlayiram.
Issue-nu aciq saxlayiram ki, kimse bilse cavablasin.

**Comment by kamranata** [comment]
> ASAN xidmətdə mənə deyildi ki, vergini 3 aydan bir ödəyə bilərsən ama dsmf və sığortanı ni gərək hər növbəti ay 20nə kimi ödəyəsən

doğrudur, gecikdirildikdə cərimə faizi gəlir.

**Comment by kamranata** [comment]
> ![image](https://user-images.githubusercontent.com/33841624/117161358-e3b59e00-add2-11eb-8f64-874f24e58200.png)
> Burada, hesabat doldurma yerində xərc kimi göstərmək yeri yoxdur siz dediyiniz kimi

![image](https://user-images.githubusercontent.com/4980999/117291064-96433a80-ae7f-11eb-8f0b-f4b4970ad97f.png)
hesabat verərkən E-bəyannamə bölməsini seçib daxil olun.

**Comment by fermanquliyev** [comment]
@kamranata men ele bilirdim bu ancaq e-VHF daki men gosterdiyim pencere ile etmek lazimdir. E-bəyənnamədən etsəm e-VHFda göstərdiyim yerdən etməyə ehtiyac olmayacaq hə?

**Comment by shahinsafarali** [comment]
@ShahriyarR Salam, bu gün vergilər nazirliyinə zəng edib dəqiqləşdirmə apardıq, ordan verilən məlumata əsasən:

Xərclərimiz cəmi: 150 + 30.42 = 180.42
Ümumi gəlir: 1690 + 1700 + 1690
Vergi məbləği: (Ümumi gəlir - Xərclər) * Vergi % = (1690 + 1700 + 1690 - 180.42) * 5%

Başqa sözlə xərclər ümumi gəlirdən çıxılır, yerdə qalan məbləğin 5%i vergi olaraq köçürülür.

**Comment by ShahriyarR** [comment]
@shahinsafarali hmmm men bele etmishdim mi, etmemishdim mi, deqiq xatirlamiram.
Oyrenib duzelish ederem. Teshekkurler comment ucun :)

**Comment by ShahriyarR** [comment]
@shahinsafarali @fermanquliyev yuxarida qeyd olunan kimidir beli.
Men hesablamani sehv gostermishem. Derhal duzeldirem.
Tesekkurler :)
